name: MacOS

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  wine-staging:
    runs-on:  macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          brew install --cask xquartz
          brew install  bison \
                        gphoto2 \
                        gst-plugins-base \
                        mingw-w64 \
                        molten-vk \
                        sdl2

      - name: Add bison & krb5 to $PATH
        run: |
          set -eu
          echo "$(brew --prefix bison)/bin" >> $GITHUB_PATH
          echo "$(brew --prefix krb5)/bin" >> $GITHUB_PATH

      - name: Get upstream-commit
        run: |
          mkdir $GITHUB_WORKSPACE/wine
          cd wine
          git init
          git fetch git://source.winehq.org/git/wine.git $($GITHUB_WORKSPACE/staging/patchinstall.py --upstream-commit) --depth=1
          git checkout $($GITHUB_WORKSPACE/staging/patchinstall.py --upstream-commit)

      - name: Run patchinstall.py --all
        run: |
          cd wine
          $GITHUB_WORKSPACE/staging/patchinstall.py DESTDIR=. --all

      - name: Configure wine64
        env:
          LDFLAGS: "-Wl,-rpath,/opt/X11/lib"
          # Avoid weird linker errors with Xcode 10 and later
          MACOSX_DEPLOYMENT_TARGET: "10.14"
        run: |
          mkdir -p $GITHUB_WORKSPACE/build
          cd $GITHUB_WORKSPACE/wine
          ./configure --prefix=$GITHUB_WORKSPACE/build \
                        --enable-win64 \
                        --without-alsa \
                        --without-capi \
                        --without-dbus \
                        --without-inotify \
                        --without-oss \
                        --without-pulse \
                        --without-udev \
                        --without-v4l2 \
                        --x-include=/opt/X11/include \
                        --x-lib=/opt/X11/lib

      - name: Build wine64
        run: |
          cd $GITHUB_WORKSPACE/wine
          make -j$(sysctl -n hw.ncpu 2>/dev/null)
          
      - name: Tar Wine
        run: |
          tar -czvf wine.tar.gz $GITHUB_WORKSPACE/build/*

      - name: Upload Wine
        uses: actions/upload-artifact@v3
        with:
          name: wine.tar.gz
          path: wine.tar.gz
